name: Initialise Repo

on:
  workflow_dispatch:
  push:
    branches: 
      - master

permissions:
  issues: write 

jobs:
  run-script:
    name: run-script
    runs-on: ubuntu-latest

    steps:
    - name: Create a new issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Test1",
          "body": "This is an automated issue created by the workflow."
        }'
        
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Test2",
          "body": "Sper sa mearga"
        }'
        
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/issues \
        -d '{
          "title": "Test3",
          "body": "Uga Buga"
        }'
    - name: Delete this workflow file
      env:
        PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      run: |
        curl -X DELETE -H "Authorization: token $PERSONAL_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/contents/.github/workflows/Initialise%20Repo.yml \
          -d '{
            "message": "Deleting Initialise Repo workflow after initial run",
            "sha": "$(curl -s -H "Authorization: token $PERSONAL_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/contents/.github/workflows/Initialise%20Repo.yml | jq -r .sha)"
          }'
